version: '3.4'
services:
  redis:
    image: redis
    container_name: dc2_redis
    ports:
      - "6379:6379"
    networks:
      - dc2_net
  mysql:
    image: mysql:8.0
    container_name: dc2_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dc2
    ports:
            - "13306:3306"
    networks:
      - dc2_net
networks:
  dc2_net:
    driver: bridge